platform :ios, '11.0'
workspace 'CoppelReto'
use_frameworks!


target 'RetoMovies' do
  use_frameworks!
  pod 'youtube-ios-player-helper'
  pod 'Firebase/Auth'
  pod 'IQKeyboardManagerSwift', '6.5.6'
  project 'RetoMovies/RetoMovies.xcodeproj'
end

target 'SDKGCommonUtils' do
  use_frameworks!
  project 'SDKGCommonUtils/SDKGCommonUtils.xcodeproj'
end

target 'SDKGServicesManager' do
  use_frameworks!
  project 'SDKGServicesManager/SDKGServicesManager.xcodeproj'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
